# Generated by Django 5.2.2 on 2025-06-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_product_brand_product_description_product_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
