# Generated by Django 5.2.2 on 2025-06-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_user_details_terms_alter_user_details_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
